### ISSUE TITLE
Null als waarde in lijst in Bundle - Condition.category

### ISSUE THREAD

**Issue by mertenssander** [Nictiz/Nictiz-R4-GPCare-ParamedicalCare#2]
https://github.com/Nictiz/Nictiz-R4-GPCare-ParamedicalCare/blob/18a7c0f59364af363832de048d71a8d93ba7e3b8/examples/hzp-ServiceRequest-example-bundle-1.json#L450

Heb dit nog niet zelf getest, maar wellicht dat het door deze FSH definitie komt:
 https://github.com/Nictiz/Nictiz-R4-GPCare-ParamedicalCare/blob/18a7c0f59364af363832de048d71a8d93ba7e3b8/examples/fsh/hzp-examples.fsh#L438
Ik meen dat dit middels:
```
* category[+] = http://snomed.info/sct#282291009 "Interpretatie van diagnose"
* category[=].text = "Diagnose"
```
Gedefinieerd zou moeten worden. Als de lijst een null based iterator id gebruikt zou de JSON een logisch gevolg zijn (en wellicht ook een bug in de FSH compiler)

**Comment by NictizEduard** [comment]
Dank je wel voor het doorgeven van de bevinding, @mertenssander. Ik heb dit opgelost in FSH en tevens de bundels opnieuw gegenereerd.
